name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
    actions: write
    contents: read


jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-22.04
    timeout-minutes: 120 # 2 hours
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.add(url = "https://github.com/JuliaPhase/AlternatingProjections.jl", rev= "develop")
            Pkg.add(url = "https://github.com/JuliaPhase/SampledDomains.jl")
            Pkg.add(url = "https://github.com/JuliaPhase/PhaseUtils.jl")
            Pkg.add(url = "https://github.com/JuliaPhase/PhasePlots.jl")
            Pkg.add(url = "https://github.com/JuliaPhase/PhaseBases.jl")
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl
        timeout-minutes: 10
